-- Event Alpha Korea — 시드 데이터
-- 재실행해도 중복이 생기지 않도록 전부 on conflict do nothing / do update.

-- ─── 운영 설정 ───────────────────────────────────────────────
insert into app_settings (id, daily_llm_budget_usd, collect_enabled, analyze_enabled, max_events_per_tick)
values (1, 3.00, true, true, 3)
on conflict (id) do nothing;

-- ─── 감시 키워드 ─────────────────────────────────────────────
insert into watch_keywords (keyword, category, priority) values
  ('관세',          'tariff_trade',           1),
  ('관세 인상',     'tariff_trade',           1),
  ('수출 제한',     'tariff_trade',           1),
  ('수입 규제',     'tariff_trade',           1),
  ('수출 통제',     'tariff_trade',           1),
  ('반도체 규제',   'tariff_trade',           1),
  ('무역 제재',     'tariff_trade',           2),
  ('보조금',        'policy_regulation',      2),
  ('세액공제',      'policy_regulation',      3),
  ('규제 완화',     'policy_regulation',      3),
  ('인허가',        'policy_regulation',      4),
  ('공급 중단',     'supply_disruption',      1),
  ('공급망 차질',   'supply_disruption',      1),
  ('부품 부족',     'supply_disruption',      2),
  ('공장 화재',     'production_halt',        1),
  ('가동 중단',     'production_halt',        1),
  ('파업',          'production_halt',        2),
  ('대규모 수주',   'major_order',            2),
  ('수주',          'major_order',            3),
  ('낙찰',          'major_order',            3),
  ('계약 체결',     'contract_change',        3),
  ('계약 해지',     'contract_change',        2),
  ('공급계약',      'contract_change',        3),
  ('인수합병',      'ma_control',             3),
  ('경영권 변경',   'ma_control',             3),
  ('지분 매각',     'ma_control',             4),
  ('자산 매각',     'asset_sale',             4),
  ('사업부 매각',   'asset_sale',             4),
  ('원유',          'commodity_price',        2),
  ('구리',          'commodity_price',        2),
  ('리튬',          'commodity_price',        2),
  ('희토류',        'commodity_price',        1),
  ('니켈',          'commodity_price',        3),
  ('LNG',           'commodity_price',        2),
  ('해상풍력',      'policy_regulation',      3),
  ('전력망',        'policy_regulation',      3),
  ('데이터센터',    'policy_regulation',      3),
  ('해협 봉쇄',     'geopolitics_logistics',  1),
  ('물류 대란',     'geopolitics_logistics',  2),
  ('운임 급등',     'geopolitics_logistics',  3)
on conflict (keyword) do update
  set category = excluded.category,
      priority = excluded.priority;

-- ─── 동의어 사전 ─────────────────────────────────────────────
-- alias(이형태) → term(정규형). 매칭 품질을 좌우하는 핵심 데이터.
-- 관리자 화면에서 계속 추가한다.
insert into synonyms (term, alias, category) values
  -- 전력기기
  ('변압기', 'transformer', 'product'),
  ('변압기', '초고압변압기', 'product'),
  ('변압기', '주상변압기', 'product'),
  ('변압기', '전력변압기', 'product'),
  ('전력망', '송배전망', 'product'),
  ('전력망', '그리드', 'product'),
  ('전력망', 'grid', 'product'),
  ('전력망', '전력계통', 'product'),
  ('전선', '케이블', 'product'),
  ('전선', '해저케이블', 'product'),
  ('개폐기', 'switchgear', 'product'),
  -- 이차전지
  ('이차전지', '2차전지', 'product'),
  ('이차전지', '배터리', 'product'),
  ('이차전지', 'battery', 'product'),
  ('이차전지', 'LIB', 'product'),
  ('양극재', '양극활물질', 'product'),
  ('음극재', '음극활물질', 'product'),
  ('분리막', 'separator', 'product'),
  ('전해액', 'electrolyte', 'product'),
  ('리튬', '탄산리튬', 'raw_material'),
  ('리튬', '수산화리튬', 'raw_material'),
  ('리튬', 'lithium', 'raw_material'),
  ('니켈', 'nickel', 'raw_material'),
  ('코발트', 'cobalt', 'raw_material'),
  ('흑연', 'graphite', 'raw_material'),
  ('희토류', '희토', 'raw_material'),
  ('희토류', 'rare earth', 'raw_material'),
  ('희토류', '네오디뮴', 'raw_material'),
  -- 반도체
  ('반도체', 'semiconductor', 'product'),
  ('메모리반도체', 'DRAM', 'product'),
  ('메모리반도체', '디램', 'product'),
  ('메모리반도체', '낸드', 'product'),
  ('메모리반도체', 'NAND', 'product'),
  ('메모리반도체', 'HBM', 'product'),
  ('시스템반도체', '비메모리', 'product'),
  ('시스템반도체', '파운드리', 'product'),
  ('반도체 장비', '전공정 장비', 'product'),
  ('반도체 장비', '후공정 장비', 'product'),
  ('반도체 소재', '포토레지스트', 'product'),
  ('반도체 소재', '불화수소', 'product'),
  ('반도체 소재', '에폭시', 'product'),
  -- 조선·해운
  ('조선', '선박 건조', 'product'),
  ('LNG운반선', 'LNG선', 'product'),
  ('LNG운반선', 'LNG carrier', 'product'),
  ('컨테이너선', '컨테이너 선박', 'product'),
  ('해운', '컨테이너 운송', 'product'),
  ('운임', '해상운임', 'product'),
  ('운임', 'SCFI', 'product'),
  -- 방산·항공
  ('방산', '방위산업', 'product'),
  ('방산', 'defense', 'product'),
  ('자주포', 'K9', 'product'),
  ('전차', 'K2', 'product'),
  -- 에너지
  ('원자력', '원전', 'product'),
  ('원자력', 'SMR', 'product'),
  ('해상풍력', '풍력발전', 'product'),
  ('해상풍력', '하부구조물', 'product'),
  ('태양광', '태양전지', 'product'),
  ('태양광', '폴리실리콘', 'product'),
  ('수소', '그린수소', 'product'),
  ('수소', '연료전지', 'product'),
  ('LNG', '액화천연가스', 'raw_material'),
  ('원유', 'WTI', 'raw_material'),
  ('원유', '두바이유', 'raw_material'),
  ('원유', 'brent', 'raw_material'),
  ('나프타', 'naphtha', 'raw_material'),
  -- 소재
  ('구리', '전기동', 'raw_material'),
  ('구리', 'copper', 'raw_material'),
  ('철광석', 'iron ore', 'raw_material'),
  ('철강', '열연', 'product'),
  ('철강', '냉연', 'product'),
  ('철강', '후판', 'product'),
  ('알루미늄', 'aluminium', 'raw_material'),
  ('알루미늄', 'aluminum', 'raw_material'),
  ('요소', '요소수', 'raw_material'),
  -- 자동차
  ('자동차부품', '차부품', 'product'),
  ('전기차', 'EV', 'product'),
  ('전기차', '전동화', 'product'),
  ('자율주행', 'ADAS', 'product'),
  -- 바이오
  ('바이오시밀러', '바이오 시밀러', 'product'),
  ('위탁생산', 'CMO', 'product'),
  ('위탁개발생산', 'CDMO', 'product'),
  ('임상시험수탁', 'CRO', 'product'),
  -- 지역
  ('미국', 'US', 'geography'),
  ('미국', 'USA', 'geography'),
  ('미국', '북미', 'geography'),
  ('중국', 'China', 'geography'),
  ('중국', '중화권', 'geography'),
  ('유럽', 'EU', 'geography'),
  ('유럽', '구주', 'geography'),
  ('일본', 'Japan', 'geography'),
  ('동남아', '아세안', 'geography'),
  ('중동', '사우디', 'geography'),
  ('인도', 'India', 'geography'),
  -- 고객 산업
  ('데이터센터', 'IDC', 'customer_industry'),
  ('데이터센터', '하이퍼스케일러', 'customer_industry'),
  ('건설', '플랜트', 'customer_industry'),
  ('조선업', '조선소', 'customer_industry'),
  ('통신', '5G', 'customer_industry'),
  ('가전', '생활가전', 'customer_industry')
on conflict (alias, term) do nothing;
